[package]
name = "bm25-jieba"
version = "0.2.0"
edition = "2021"

[lib]
name = "bm25_jieba"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
jieba-rs = "0.8.1"
