[package]
name = "bm25"
version = "0.1.0"
edition = "2021"

[lib]
name = "bm25"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
jieba-rs = "0.8.1"
